plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
      - type: update
        release: patch
      - type: new
        release: minor
      - type: del
        release: major
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
preset: conventionalcommits
